throw( fault_name, fault_data )